-- ============================================
-- IT-Dashboard Autohaus Seitz – Initialdaten
-- 100 Projekte aus der Original-HTML-Datei
-- Im Supabase SQL Editor nach schema.sql ausfuehren
-- ============================================

INSERT INTO projekte (prio, titel, projektnr, fertig, cluster) VALUES
('A++', 'Bau-Projekt: Seat Weingarten mit Schlüsseltresor', NULL, 100, 'Bauprojekte / Standortausbau'),
('B', 'CrossCam für PZ Augsburg', NULL, 100, 'Bauprojekte / Standortausbau, Cross / Werkstatt / Video'),
('A++', 'Bau-Projekt: Verwaltung/DLZ/Parkhaus mit Schlüsseltresor, mit Secontec Alarmanlage', NULL, 100, 'Bauprojekte / Standortausbau, Physical Security / Schließanlagen'),
('A++', 'Bau-Projekt: PZ Augsburg mit Schlüsseltresor, mit Secontec Alarmanlage', NULL, 100, 'Bauprojekte / Standortausbau, Physical Security / Schließanlagen'),
('A', 'Neues ControllingTool evaluieren: ITPM / MARC / Numbero Cockpit (Cloud !)', '#400#', 100, 'Controlling / Data & Analytics'),
('?', 'Cross MSA SM 1x, LK 1x ff. (Anforderung Niebauer+Vogler) nur PO!', NULL, 100, 'Cross / Werkstatt / Video'),
('A++', 'CrossCam für alle Seat Betriebe (ISO-Relevant)', NULL, 100, 'Cross / Werkstatt / Video'),
('B', 'CrossCam / MSA --> MSR Erweiterungen auf zus. Betriebe', '#540#', 100, 'Cross / Werkstatt / Video'),
('?', 'D3 Eingangsrechnung: Ausrüstung mit 2 Mon.', NULL, 100, 'Dokumentenmanagement / D3 / E-Rechnung'),
('A++', 'Smartserver --> d3 EdgeBox ersetzen wg. Q6 (Step1: Audi Standorte)', NULL, 100, 'Dokumentenmanagement / D3 / E-Rechnung'),
('A++', 'D3 Eingangsrechnung aktivieren', NULL, 100, 'Dokumentenmanagement / D3 / E-Rechnung'),
('A', 'ELO-Ablöse durch d3 Archiv (Migration) + Prüfung/Freigabe interne Belastungen', NULL, 100, 'Dokumentenmanagement / D3 / E-Rechnung'),
('A', 'Konsolidierung Mobile Device Management (MS intune)', NULL, 100, 'Endpoint & MDM / Intune / Mobile'),
('A++', 'IT-Sicherheit: VPN-Zugriff via Notebook (~150x)', NULL, 100, 'IT-Security / Endpoint / Hardening'),
('A++', 'IT-Sicherheit: Pentest (Handys für Werkstatt + USB-Anschluß sperren)', NULL, 100, 'IT-Security / Endpoint / Hardening'),
('A++++', 'IT-Sicherheit: Antivirus FireEye Endpoint Detection and Response/Monitoring', '#120#', 100, 'IT-Security / Endpoint / Hardening'),
('A+', 'IT-Sicherheit: K-Business: Notfallplan erstellen', '#110#', 100, 'IT-Security / Endpoint / Hardening'),
('A+', 'Umbrella', NULL, 100, 'IT-Security / Endpoint / Hardening'),
('A++', 'Matrix Endpoint Management System Upgrade', NULL, 100, 'IT-Security / Endpoint / Hardening'),
('A++++', 'IT-Sicherheit präventiv: Cisco Umbrella', '#140#', 100, 'IT-Security / Endpoint / Hardening, Telefonie / Teams Migration'),
('A++', 'Office2013 --> Office2021 (Deadline April 2023)', '#300#', 100, 'Microsoft 365 / Office / SharePoint'),
('A++', 'Viadesk durch Sharepoint ersetzen', '#320#', 100, 'Microsoft 365 / Office / SharePoint'),
('A++', 'Telekom MPLS-Datennetz Redesign (LWL VZ,AZ,MM)', NULL, 100, 'Netzwerk / Switches / SD-WAN'),
('A++', 'Server-Upgrade (Win Server 2012R2 zu Win Server 2019)', '#330#', 100, 'Netzwerk / Switches / SD-WAN, Server / Virtualisierung / Backup'),
('A', 'K-Business: Netzwerküberwachung (Switch/WLAN) mit Servicevertrag', '#160#', 100, 'Netzwerk / Switches / SD-WAN, WLAN / Access Points'),
('A++', 'NORA: Umzug von MM --> LK (gemeinsamer Bestellmandant)', NULL, 100, 'NORA / Standortwechsel'),
('A', 'NORA: Umzug an neuen Standort zum 7.5.24', NULL, 100, 'NORA / Standortwechsel'),
('A', 'Schließanlage VG+PA', NULL, 100, 'Physical Security / Schließanlagen'),
('A++', 'DOM Schließanlage NO', NULL, 100, 'Physical Security / Schließanlagen'),
('A++', 'Telekom vCloud ablösen (abgekündigt für 12/23)', '#310#', 100, 'Provider / Partnerwechsel'),
('A', 'Seitz Akademie', NULL, 100, 'Schulungen / LMS'),
('A+', 'Datensicherung Support Ende', NULL, 100, 'Server / Virtualisierung / Backup'),
('A+', 'Zentrale USV ersetzen', NULL, 100, 'Server / Virtualisierung / Backup'),
('A', 'VCenter 2026 end of support', NULL, 100, 'Server / Virtualisierung / Backup'),
('A', 'SG: Standort um Marke Seat/Cupra erweitern zum 1.1.24', NULL, 100, 'Sonstiges'),
('A', 'CROSS PartsMobile (Ablöse Partscan) AZ/SZ/IS/LI/WA/LK + 3 neue LK/SG/KE', '#500#', 100, 'Sonstiges'),
('A', 'Skoda-Betriebe mit ServiceKey ausrüsten (ISO relevant)', '#510#', 100, 'Sonstiges'),
('A', 'DLZ: HomeBase', '#420#', 100, 'Sonstiges'),
('A', 'Thin-Clients in den Werkstätten gegen PCs ersetzen', '#340#', 100, 'Sonstiges'),
('A', 'GW-Pricing (IT Krebs: eautoseller) DAT3 aktivieren', NULL, 100, 'Sonstiges'),
('A', 'Firmenkonsolidierung AZ', NULL, 100, 'Sonstiges'),
('A', 'Ausbau Zentrale Kundenbetreuung', NULL, 100, 'Sonstiges'),
('A++', 'ETMaster Hardware --> Software Umzug (Neue NL-Server nötig 14x á 4T€)', '#370#', 100, 'Sonstiges'),
('A++', 'Odis 8', NULL, 100, 'Sonstiges'),
('A++', 'Windows 10 Major Update 21H2', NULL, 100, 'Sonstiges'),
('A++', 'KS: Erneuerung der MEKmedia Multimedia-Komponenten', NULL, 100, 'Sonstiges'),
('A++', 'Z-GWL + Buha: 26 Thinclients ersetzen gegen Notebooks', NULL, 100, 'Sonstiges'),
('A++', 'Audi Multimedia-Komponenten (DRM) AZ/MM/LD (ISO-relevant)', NULL, 100, 'Sonstiges'),
('A+++', 'Illertissen anbinden (IL) Betriebsnr. 69900', NULL, 100, 'Sonstiges'),
('A+++', 'Firewall activ active', NULL, 100, 'Sonstiges'),
('B', 'Lack-Standorte erhalten neue Hard- und Software VZ,MM,SF,WA', '#520#', 100, 'Sonstiges'),
('B', 'Mobiler Verkäuferarbeitsplatz 90x', NULL, 100, 'Sonstiges'),
('B', 'automatisierte Google-Antworten', NULL, 100, 'Sonstiges'),
('C', '1 Domain-Controller (Konzept)', NULL, 100, 'Sonstiges'),
('C', 'YOMA: Track & Trace', NULL, 100, 'Sonstiges'),
('A', 'DLZ: PoC Logistik-Software einführen (Kasasi)', '#410#', 100, 'Sonstiges'),
('A', 'Erfassung aller Fahrzeugtransporte in der Gruppe', NULL, 100, 'Sonstiges'),
('A+', 'Einheitliche Mail-Domain', NULL, 100, 'Sonstiges'),
('A', 'Austausch alter PC-Hardware (mind. 150 PCs pro Jahr)', '#350#', 100, 'Sonstiges'),
('A', 'Volkswagen/NFZ: Car-Configurator CI-Änderungen VZ/RV/MMVW+LD+SF+IS', NULL, 100, 'Sonstiges'),
('A++', 'zentrales Telefoncontrolling', NULL, 100, 'Sonstiges'),
('A++', 'Einbindung MM in Leasingrücknahme', NULL, 100, 'Sonstiges'),
('B', 'CI-Änderungen: VZ/RV/MMVW+LD+SF+IS+SM', '#530#', 100, 'Sonstiges'),
('B', 'Testphase Fahrzeugverortung mit Kundenansicht (Track&Trace)', NULL, 100, 'Sonstiges'),
('A+++', 'Telefonie: Teams-Migration der Cisco-Standorte (Deadline 31.12.23)', '#200#', 100, 'Telefonie / Teams Migration'),
('C', 'Einheitliche Ausrüstung von Besprechungsräumen (Cisco Roomkits/Poly)', NULL, 100, 'Telefonie / Teams Migration'),
('A', 'WLAN modernisieren. Cisco IOS XE Bengaluru 17.5.1 oder höher.', NULL, 100, 'WLAN / Access Points'),
('B', 'Konsolidierung WIFI-Infrastruktur (DNA)', NULL, 100, 'WLAN / Access Points'),
('A', 'Zeiterfassung (unprod. Mitarbeiter) per App – Step 1: Verwaltung', '#450#', 100, 'Zeiterfassung'),
('A+', 'IT-Sicherheit: Härtung Active Directory', '#160#', 95, 'IT-Security / Endpoint / Hardening'),
('A', 'Begleitung VWFS-Dealershop (Leasingstrecke)', NULL, 90, 'Sonstiges'),
('A', 'Austausch alter Netzwerk-Komponenten', '#360#', 80, 'Netzwerk / Switches / SD-WAN'),
('A+', 'Umstellung der DOM-Softwareverwaltung', NULL, 75, 'Physical Security / Schließanlagen'),
('A', 'd3 Vertragsmanagement ggf. mit elektronischer Signatur (ELO --> d3)', NULL, 70, 'Dokumentenmanagement / D3 / E-Rechnung'),
('A+', 'IT-Sicherheit: Zugriff auf Firmengeräte einschränken mit Office365 EMS E3 2FA', '#130#', 70, 'IT-Security / Endpoint / Hardening'),
('A+', 'Filesystem Groups -> Office365', NULL, 70, 'Microsoft 365 / Office / SharePoint'),
('A', 'IT-Sicherheit: Zutrittssicherung der EDV-Räume an Außen-Standorten (Kentix/DOM)', '#150#', 50, 'IT-Security / Endpoint / Hardening, Physical Security / Schließanlagen'),
('A', 'Großabnehmer CRM (Kontakte, Ansprechpartner, Quartalsberichte)', NULL, 45, 'Sonstiges'),
('A+', 'Intune implementieren PCs', NULL, 40, 'Endpoint & MDM / Intune / Mobile'),
('B', 'SAP Lifecycle begleiten (2026 Migration S/4Hana)', NULL, 40, 'SAP / S4HANA'),
('A', 'MM - NW/GW-Handling analog DLZ', NULL, 40, 'Sonstiges'),
('A+', 'Mitarbeiter On-/Offboarding Workflow', '#460#', 35, 'HR / On- & Offboarding / Workflows'),
('B', 'Einführung zentrales LMS (Arbeitsschutz, div. Schulungen)', NULL, 30, 'Schulungen / LMS'),
('B', 'd3 Serviceakte (für zentrale Fakturierung)', NULL, 20, 'Dokumentenmanagement / D3 / E-Rechnung'),
('A', 'O365 neuen Partner finden (Skysystems ablösen)', NULL, 20, 'Microsoft 365 / Office / SharePoint, Provider / Partnerwechsel'),
('A', 'Prozesse GW-Abteilung (Inzahlungnahme, Händlerkommunikation, Bilder)', NULL, 20, 'Sonstiges'),
('A+', 'Seitz-Datalake (Supabase ?)', NULL, 15, 'Controlling / Data & Analytics'),
('B', '2026: SAP Migration S/4Hana', NULL, 10, 'SAP / S4HANA'),
('A', 'Robot Desktop Automation (Aubex Cross Auftragsvorbereitung)', NULL, 10, 'Sonstiges'),
('A', 'PO Umbau', NULL, 10, 'Sonstiges'),
(NULL, 'Seebacher to Seitz', NULL, 10, 'Sonstiges'),
('A+', 'MPLS durch SDWAN', NULL, 5, 'Netzwerk / Switches / SD-WAN'),
('A+', 'Neuwagen-Akt Workflow Ablöse CarI Digitalisierung Dispo', NULL, 0, 'HR / On- & Offboarding / Workflows'),
('A', 'IT-Sicherheit: Festplatten verschlüsseln (Bitlocker)', NULL, 0, 'IT-Security / Endpoint / Hardening'),
('A', 'Modernisierung Classifier', NULL, 0, 'Sonstiges'),
('A', 'Digitale Kundenbetreuung (KI telefoniert)', NULL, 0, 'Sonstiges'),
('A', 'Penetrationstest', NULL, 0, 'Sonstiges'),
('B', 'Passwortsafe für Mitarbeiterinnen', NULL, 0, 'Sonstiges'),
('B', 'Digitale Werkstatt: CROSS Werkstattplaner Pilot', NULL, 0, 'Sonstiges'),
('A+', 'Antivirus neu', NULL, 0, 'IT-Security / Endpoint / Hardening');
